# Generated by Django 5.1.2 on 2024-11-15 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POST', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='districtname',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='pincodeno',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
