# Generated by Django 5.1.2 on 2024-11-15 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POST', '0002_user_districtname_user_pincodeno'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('approved', 'Approved'), ('reject', 'Reject')], default='applied', max_length=20),
        ),
    ]
