# Generated by Django 5.1.2 on 2024-12-23 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POST', '0003_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='parcel_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
