# Generated by Django 5.1.2 on 2024-12-23 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('POST', '0004_postmodel_parcel_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postmodel',
            old_name='receiver_condact',
            new_name='receiver_contact',
        ),
        migrations.RenameField(
            model_name='postmodel',
            old_name='sender_condact',
            new_name='sender_contact',
        ),
    ]
