# Generated by Django 5.1.2 on 2024-12-26 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POST', '0005_rename_receiver_condact_postmodel_receiver_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='postoffice',
            field=models.CharField(choices=[('mainpostoffice', 'Main_postoffice'), ('subpostoffice', 'Sub_postoffice')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
