# Generated by Django 5.1.2 on 2025-01-12 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POST', '0007_alter_postmodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
