# Generated by Django 5.1.2 on 2025-01-19 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POST', '0008_alter_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='postoffice',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
