# Generated by Django 5.1.2 on 2025-01-19 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POST', '0009_postoffice_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postoffice',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
