# Generated by Django 5.1.4 on 2025-01-20 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POST', '0010_alter_postoffice_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='receiver_email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
