# Generated by Django 5.1.4 on 2025-01-20 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POST', '0011_postmodel_receiver_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='postman',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='postman_images/'),
        ),
    ]
