# Generated by Django 5.1.2 on 2025-01-25 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POST', '0012_postman_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='reshedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resheduled_date', models.DateField()),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='POST.postmodel')),
            ],
        ),
    ]
