# Generated by Django 5.1.2 on 2025-02-08 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POST', '0014_rename_reshedule_reschedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='reschedule_status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
