# Generated by Django 5.1.2 on 2025-02-08 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POST', '0015_postmodel_reschedule_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='receiver_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
