# Generated by Django 5.1.2 on 2025-02-08 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POST', '0016_alter_postmodel_receiver_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='reschedule_status',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
