# Generated by Django 5.1.2 on 2025-02-08 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POST', '0017_alter_postmodel_reschedule_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='reschedule_status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
