# Generated by Django 5.1.2 on 2025-02-23 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POST', '0018_alter_postmodel_reschedule_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='status',
            field=models.CharField(choices=[('itempacked', 'item_packed'), ('itemdispatched', 'item_dispatched'), ('itemoutfordelivery', 'item_outfordelivery'), ('itemdelivered', 'item_delivered'), ('doorclosed', 'door_closed'), ('returned', 'returned'), ('rescheduled', 'rescheduled')], max_length=100),
        ),
    ]
