# Generated by Django 5.1.2 on 2025-02-23 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POST', '0020_reschedule_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='parcel_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='reschedule',
            name='parcel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='POST.postmodel', to_field='parcel_id'),
        ),
    ]
