# Generated by Django 5.1.6 on 2025-02-24 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POST', '0021_alter_postmodel_parcel_id_alter_reschedule_parcel'),
    ]

    operations = [
        migrations.AddField(
            model_name='reschedule',
            name='payment_status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
