# Generated by Django 5.1.6 on 2025-02-24 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POST', '0022_reschedule_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reschedule',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
