# Generated by Django 5.1.2 on 2025-03-01 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POST', '0025_rename_postman_username_postmodel_postman_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postman',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
