# Generated by Django 5.1.2 on 2025-03-02 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('POST', '0028_user_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_login',
        ),
    ]
