# Generated by Django 5.1.2 on 2025-03-03 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POST', '0029_remove_user_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postman',
            name='postman_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='sender_contact',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postoffice',
            name='postoffice_id',
            field=models.IntegerField(),
        ),
    ]
