# Generated by Django 5.1.2 on 2025-03-03 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POST', '0030_alter_postman_postman_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='user_email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
