# Generated by Django 5.1.2 on 2025-03-04 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('POST', '0031_postmodel_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='user_email',
        ),
        migrations.RemoveField(
            model_name='postoffice',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='postoffice',
            name='longitude',
        ),
    ]
