# Generated by Django 5.1.2 on 2025-03-08 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POST', '0032_remove_postmodel_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postman',
            name='otp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='otp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
