# Generated by Django 5.1.2 on 2025-03-08 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POST', '0033_postman_otp_user_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=8),
        ),
    ]
